name: CI

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1

    - name: Install and build
      run: npm ci && npm run build
